name: Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Install Python
        run: |
          apt update -y
          apt install -y \
            python3 \
            python3-pip \
            build-essential \
            cmake \
            curl

      - name: Install aqtinstall
        run: |
          python3 -m pip install aqtinstall

      - name: Install Qt
        run: |
          aqt install-qt linux desktop 6.7.3 linux_gcc_64

      #      - name: Install Qt
      #        uses: jurplel/install-qt-action@v4
      #        with:
      #          version: '6.7.3'

      - name: Build clide
        run: |
          cd clide
          cargo b
